name: Build Pull request
on:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
  TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  NEXT_PUBLIC_TINA_BRANCH: ${{ github.head_ref }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: Node 18 sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: yarn/action-setup@v4
        name: Install yarn
        id: yarn-install
        with:
          version: 9
          run_install: false

      - name: Get yarn store directory
        id: yarn-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(yarn store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-yarn-store-${{ hashFiles('**/yarn-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-store-

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
